Repository Arelith-Server/are-model, pull requests merged in 2024-05, with the labels that each got.

#1057 Black Blade of Disaster reskin
  mdl/ascii/items/weapons/ours/wswgs_b_091.mdl
  mdl/ascii/items/weapons/ours/wswgs_m_091.mdl
  mdl/ascii/items/weapons/ours/wswgs_t_091.mdl
  static/mtr/items/weapons/sp/bbod.mtr
  static/shader/fst_bbod.shd
  static/shader/inc_bbod.shd
  static/shader/vsvt_bbod.shd
  textures/lossy_keep/tga/items/ours/bbod.tga
  textures/lossy_keep/tga/items/ours/iwswgs_b_091.tga
  textures/lossy_keep/tga/items/ours/iwswgs_m_091.tga
  textures/lossy_keep/tga/items/ours/iwswgs_t_091.tga
Labels: enhancement

#1059 Improvement: Overriding w_metal_tex
  textures/lossy_keep/tga/items/ours/w_metal_tex.tga
Labels: question

#1066 Correctly Assigns Doll + Bone Fetish textures
  mdl/ascii/items/weapons/ours/it_torch_028.mdl
  mdl/ascii/items/weapons/ours/it_torch_029.mdl
  mdl/ascii/items/weapons/ours/it_torch_030.mdl
  mdl/ascii/items/weapons/ours/it_torch_031.mdl
  mdl/ascii/items/weapons/ours/it_torch_032.mdl
Labels: BUGFIX

#1064 Sf/t_08 dagger fix
  mdl/ascii/items/weapons/various/wswdg_t_081.mdl
  mdl/ascii/items/weapons/various/wswdg_t_082.mdl
  mdl/ascii/items/weapons/various/wswdg_t_083.mdl
  mdl/ascii/items/weapons/various/wswdg_t_084.mdl
Labels: BUGFIX
