Repository Arelith-Server/are-model, pull requests merged in 2025-02, with the labels that each got.

#1264 Remove Duplicated Shield Texture
  textures/lossy_keep/tga/items/various/al_roughsteel_dk.tga
Labels: BUGFIX

#1263 Added 9 male elf heads & 1 human
  mdl/ascii/body/heads/pme0_head032.mdl
  mdl/ascii/body/heads/pme0_head033.mdl
  mdl/ascii/body/heads/pme0_head034.mdl
  mdl/ascii/body/heads/pme0_head035.mdl
  mdl/ascii/body/heads/pme0_head036.mdl
  mdl/ascii/body/heads/pme0_head037.mdl
  mdl/ascii/body/heads/pme0_head038.mdl
  mdl/ascii/body/heads/pme0_head039.mdl
  mdl/ascii/body/heads/pme0_head040.mdl
  mdl/ascii/body/heads/pmh0_head099.mdl
  textures/lossy_keep/plt/heads/pme0_head032.plt
  textures/lossy_keep/plt/heads/pme0_head033.plt
  textures/lossy_keep/plt/heads/pme0_head034.plt
  textures/lossy_keep/plt/heads/pme0_head035.plt
  textures/lossy_keep/plt/heads/pme0_head036.plt
  textures/lossy_keep/plt/heads/pme0_head037.plt
  textures/lossy_keep/plt/heads/pme0_head038.plt
  textures/lossy_keep/plt/heads/pme0_head039.plt
  textures/lossy_keep/plt/heads/pme0_head040.plt
  textures/lossy_keep/plt/heads/pmh0_head099.plt
  textures/lossy_keep/plt/pmh0_head099.plt
Labels: enhancement

#1260 New Whip
  mdl/ascii/items/weapons/various/wwhip_b_021.mdl
  mdl/ascii/items/weapons/various/wwhip_b_022.mdl
  mdl/ascii/items/weapons/various/wwhip_b_023.mdl
  mdl/ascii/items/weapons/various/wwhip_b_024.mdl
  mdl/ascii/items/weapons/various/wwhip_b_031.mdl
  mdl/ascii/items/weapons/various/wwhip_b_032.mdl
  mdl/ascii/items/weapons/various/wwhip_b_033.mdl
  mdl/ascii/items/weapons/various/wwhip_b_034.mdl
  mdl/ascii/items/weapons/various/wwhip_m_021.mdl
  mdl/ascii/items/weapons/various/wwhip_m_022.mdl
  mdl/ascii/items/weapons/various/wwhip_m_023.mdl
  mdl/ascii/items/weapons/various/wwhip_m_024.mdl
  textures/lossy_keep/tga/items/various/iwwhip_b_021.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_022.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_023.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_024.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_031.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_032.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_033.tga
  textures/lossy_keep/tga/items/various/iwwhip_b_034.tga
  textures/lossy_keep/tga/items/various/iwwhip_m_021.tga
  textures/lossy_keep/tga/items/various/iwwhip_m_022.tga
  textures/lossy_keep/tga/items/various/iwwhip_m_023.tga
  textures/lossy_keep/tga/items/various/iwwhip_m_024.tga
Labels: enhancement, question

#1267 Add various fixtures
  mdl/ascii/placeables/new/ours/plc_bar_flat.mdl
  mdl/ascii/placeables/new/ours/plc_hookah.mdl
  mdl/ascii/placeables/new/ours/plc_ped.mdl
  mdl/ascii/placeables/new/ours/plc_pedhndblk.mdl
  mdl/ascii/placeables/new/ours/plc_pedhndbrn.mdl
  mdl/ascii/placeables/new/ours/plc_pedhndgry.mdl
  mdl/ascii/placeables/new/ours/plc_pedshrt.mdl
  mdl/ascii/placeables/new/ours/plc_pedstnblk.mdl
  mdl/ascii/placeables/new/ours/plc_pedstnbrn.mdl
  mdl/ascii/placeables/new/ours/plc_pedstngry.mdl
  mdl/ascii/placeables/new/ours/plc_pedwri.mdl
  mdl/ascii/placeables/new/ours/plc_pedwrishrt.mdl
  static/mtr/placeables/plc_hookah.mtr
  static/walkmesh/placeables/new/ours/plc_hookah.pwk
  textures/lossless/tga/placeables/new/ours/plc_ped.tga
  textures/lossless/tga/placeables/new/ours/plc_pedbk.tga
  textures/lossless/tga/placeables/new/ours/plc_pedhndblk.tga
  textures/lossless/tga/placeables/new/ours/plc_pedhndbrn.tga
  textures/lossless/tga/placeables/new/ours/plc_pedhndgry.tga
  textures/lossless/tga/placeables/new/ours/plc_pedstnblk.tga
  textures/lossless/tga/placeables/new/ours/plc_pedstnbrn.tga
  textures/lossless/tga/placeables/new/ours/plc_pedstngry.tga
  textures/lossy_keep/dds/placeables/ours/plc_hookah_d.dds
  textures/lossy_keep/dds/placeables/ours/plc_hookah_n.dds
  textures/lossy_keep/dds/placeables/ours/plc_hookah_r.dds
  textures/lossy_keep/dds/placeables/ours/plc_hookah_s.dds
Labels: enhancement

#1257 Fixes the fishing rod icons
  textures/lossy_keep/tga/items/ours/iwfsrd_m_011.tga
  textures/lossy_keep/tga/items/ours/iwfsrd_m_012.tga
  textures/lossy_keep/tga/items/ours/iwfsrd_m_013.tga
Labels: BUGFIX

#1277 Fixes missing lion model and texture
  mdl/ascii/creatures/c_mlion.mdl
  textures/lossy_keep/dds/creatures/c_mlion.dds
Labels: BUGFIX

#1276 Oriental Placeables for SK
  mdl/ascii/placeables/new/various/ori_c01.mdl
  mdl/ascii/placeables/new/various/ori_c02.mdl
  mdl/ascii/placeables/new/various/ori_c03.mdl
  mdl/ascii/placeables/new/various/ori_d01.mdl
  mdl/ascii/placeables/new/various/ori_d03.mdl
  mdl/ascii/placeables/new/various/ori_f05.mdl
  mdl/ascii/placeables/new/various/ori_f06.mdl
  mdl/ascii/placeables/new/various/ori_f07.mdl
  mdl/ascii/placeables/new/various/ori_f08.mdl
  mdl/ascii/placeables/new/various/ori_f09.mdl
  mdl/ascii/placeables/new/various/ori_f11.mdl
  mdl/ascii/placeables/new/various/ori_f12.mdl
  mdl/ascii/placeables/new/various/ori_f13.mdl
  mdl/ascii/placeables/new/various/ori_m01.mdl
  mdl/ascii/placeables/new/various/ori_m06.mdl
  mdl/ascii/placeables/new/various/ori_m07.mdl
  mdl/ascii/placeables/new/various/psp_c01.mdl
  mdl/ascii/placeables/new/various/rkg_plc_20.mdl
  static/walkmesh/placeables/new/various/ori_d01.pwk
  static/walkmesh/placeables/new/various/ori_d03.pwk
  static/walkmesh/placeables/new/various/ori_f11.pwk
  static/walkmesh/placeables/new/various/ori_f13.pwk
  static/walkmesh/placeables/new/various/ori_m01.pwk
  static/walkmesh/placeables/new/various/ori_m06.pwk
  static/walkmesh/placeables/new/various/ori_m07.pwk
  static/walkmesh/placeables/new/various/psp_c01.pwk
  static/walkmesh/placeables/new/various/rkg_plc_20.pwk
  textures/lossless/tga/placeables/new/various/OriArt_256256.tga
  textures/lossless/tga/placeables/new/various/Tatami1_128.tga
  textures/lossless/tga/placeables/new/various/win1_64x64.tga
  textures/lossless/tga/placeables/new/various/win2_64x64.tga
  textures/lossless/tga/vfx/tx_black.tga
  textures/lossy_keep/dds/placeables/various/tx_ori_stone.dds
  textures/lossy_keep/dds/placeables/various/tx_ori_tori.dds
Labels: enhancement

#1278 Fix Oriental Lantern
  mdl/ascii/placeables/new/various/ori_f11.mdl
  textures/lossy_keep/dds/placeables/various/plc_ori_lant.dds
Labels: BUGFIX
